### ISSUE TITLE
No examples of `path` or `dockerfile` options

### ISSUE THREAD

**Issue by bobvanderlinden** [docker/build-push-action#51]
I'm working on a project that has multiple `Dockerfile`s, each of them in a separate directory. One of those is named `api`, so the dockerfile is in `api/Dockerfile`. I have the following in my workflow:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        path: api
        username: companyusername
        password: companypassword
        repository: company/myproject/api
        registry: companyregistry
        tags: latest
```

I get the following error:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/api/Dockerfile: no such file or directory
```

However, I see the `checkout` action logging the following:

```
Initializing the repository
  /usr/bin/git init /home/runner/work/myproject/myproject
```

From the documentation it is unclear that I should be using some variable to determine `/home/runner/work/myproject/myproject` instead of `/github/workspace/`. What am I doing wrong?

I also tried using `dockerfile:`, but also with the same results: always relative to `/github/workspace`.

**Comment by yordis** [comment]
@bobvanderlinden use `uses: actions/checkout@v1` for now since it seems that the action is broken with `v2`

**Comment by bobvanderlinden** [comment]
I now have the following:

```
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        path: api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mycompany/myproject/api
        registry: ${{ secrets.DOCKER_REGISTRY }}
        tags: latest
```

and I'm still seeing:

```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/api/Dockerfile: no such file or directory
```

**Comment by yordis** [comment]
I have the following

```
name: "Release"

on:
  push:
    branches:
      - "production"

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish image
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: org/repo/name
          tag_with_ref: true
          tag_with_sha: true
```

And it works.

Make sure you have a `Dockerfile` in the root of the project, double-check that.

**Comment by bobvanderlinden** [comment]
Your example doesn't have a path nor a dockerfile option. My project doesn't have a Dockerfile on the root of the repository, which is why I was forced to use the path option.

**Comment by sau00** [comment]
Got the same issue as bobvanderlinden, looks like path option doesn't work at all.

**Comment by sau00** [comment]
Alright, I get it now.
If you want to use `path` and `dockerfile` at the same time, you should make sure that your dockerfile setting matches this pattern `{path}/%Dockerfile%`. Cause by default it is `{path}/Dockerfile`.

Example:

I have my dockerfile with name `Dockerfile.txt` in `./backend/` folder, then my options should look like
`
path: backend
dockerfile: backend/DK
`

**Comment by jonkight** [comment]
I'm seeing a similar issue with the following:
```
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my/repo
          tags: latest
          path: src/go/server
```

My Dockerfile is located at `./src/go/server/Dockerfile`. Seeing the following:

```
unable to prepare context: path "src/go/server" not found
```

Any ideas what I'm missing?

**Comment by bobvanderlinden** [comment]
@sau00 that is quite useful to know. Such examples could be useful to have in the readme.

@jonkight did you do a checkout step?

**Comment by jonkight** [comment]
@bobvanderlinden 
Great point! That was exactly my problem and everything works as expected now with the config I mentioned above. Not sure why I thought it would work without it, but at some point I removed the checkout I guess. Thanks for responding so quickly.

**Comment by jonkight** [comment]
@sau00 Thanks for your comment as well. It helped me validate what I was testing.

**Comment by bobvanderlinden** [comment]
If that works for you I have to revisit my example again, something must be wrong on my side of things.

**Comment by jonkight** [comment]
Here's what I got working as a test. Hopefully it helps.

```
name: Build, test, and push Docker image

on: pull_request

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my/repo
          tags: latest
          path: src/go/server
```

**Comment by joebone** [comment]
Similar issue, but not sure how to resolve it...

Directory structure is:
/root/src/<projects with individual dockerfiles>

The build context needs to be set to /root/src/,
and the Dockerfiles would be in [ /src/projecta/dockerfile, /src/projectb/dockerfile ] etc... but the context has to be the parent in order for the internal compilation step to be able to pull in inter-project dependencies.

running from a command line would be something along the lines of:
docker build -f Dockerfile ".."

or from the root:

docker build -f "./src/projecta/Dockerfile" "./src".

How can I represent this structure, as it seems the path is completely ignored..

**Comment by crazy-max** [comment]
Hi,

This will be solved through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92) as it's written as a typescript-action to be as closed as possible of the GitHub Runner during its execution. You can already try it with:

* https://github.com/docker/setup-buildx-action
* https://github.com/docker/setup-qemu-action
* https://github.com/docker/login-action

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.

**Comment by bobvanderlinden** [comment]
That looks good! Thanks a lot :+1:

**Comment by dinvlad** [comment]
We're still seeing the same error, even with `@v2`. I wonder what that could be?
```yaml
- uses: docker/setup-buildx-action@v1
- uses: docker/build-push-action@v2
  with:
    context: ./path/to/context
    tags: docker/image/name:latest
```
Result:
```
Run docker/build-push-action@v2
  with:
    context: ./path/to/context
    push: true
    tags: docker/image/name:latest
    file: ./Dockerfile
    pull: false
    no-cache: false
    load: false
    github-token: ***
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --tag docker/image/name:latest --iidfile /tmp/docker-build-push-XMCDtE/iidfile --file ./Dockerfile --push ./path/to/context
time="2020-10-02T03:11:16Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
#2 [internal] load .dockerignore
#2 transferring context: 77B 0.0s done
#2 DONE 0.0s

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2B 0.0s done
#1 DONE 0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount934169700/Dockerfile: no such file or directory
Error: The process '/usr/bin/docker' failed with exit code 1
```
I have verified that our `./path/to/context` does contain `Dockerfile` - not sure where else to look.
Thanks!

**Comment by dinvlad** [comment]
OK, so our mistake was that `file:` is not relative to `context:`! We have to specify it like this:
```yaml
- uses: docker/build-push-action@v2
  with:
    context: ./path/to/context
    file: ./path/to/context/Dockerfile
    tags: docker/image/name:latest
```
It would be nice to document it more explicitly :)

**Comment by crazy-max** [comment]
@dinvlad 

> OK, so our mistake was that `file:` is not relative to `context:`!

This is exactly the same behavior for `docker build`

**Comment by guumaster** [comment]
We have this same issue in our workflow. And I think the documentation is not entirely clear. If you have to specify a context path, be sure to add a step with the check out action. 
```
# This Checkout is necessary when using a context in docker/build-push-action
- name: Checkout
  uses: actions/checkout@v2
....
- uses: docker/build-push-action@v2
  with:
    context: ./path/to/context
    file: ./path/to/context/Dockerfile
    tags: docker/image/name:latest
```

**Comment by crazy-max** [comment]
@guumaster See #189

**Comment by guumaster** [comment]
@crazy-max thanks. but I think is not the same issue.

 No matter what you put on `file:` (the default works ok), if you add a `context:` path, you **need** to also add the code checkout action explicitly too. Otherwise, it will complain with the error `unable to prepare context: ... folder not found` error.

**Comment by crazy-max** [comment]
@guumaster 

> thanks. but I think is not the same issue.

Sorry that's this one: https://github.com/docker/build-push-action/issues/120#issuecomment-691507706. See also [Git context](https://github.com/docker/build-push-action/#git-context) and [Path context](https://github.com/docker/build-push-action/#path-context).

**Comment by guumaster** [comment]
@crazy-max that's the one. And you are rigth that it is in the docs, but it seems clear once you already had the issue. 

Is it a good idea to add this info in the `TROUBLESHOOTING.md` section? I can make a PR with it.

**Comment by crazy-max** [comment]
@guumaster Sure feel free to open a PR.

**Comment by vot4anto** [comment]
> @crazy-max thanks. but I think is not the same issue.
> 
> No matter what you put on `file:` (the default works ok), if you add a `context:` path, you **need** to also add the code checkout action explicitly too. Otherwise, it will complain with the error `unable to prepare context: ... folder not found` error.

@guumaster thanks to your suggestion I finally go out from a nightmare buildx on github action
