### ISSUE TITLE
push to hub.docker.com fails with `denied: requested access to the resource is denied`

### ISSUE THREAD

**Issue by bastelfreak** [docker/build-push-action#88]
Hi!
thanks for the awesome action! I added it to my workflow on https://github.com/voxpupuli/vox-pupuli-tasks

```yaml
name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config set path vendor/bundle
        bundle config set jobs $(nproc)
        bundle config set without development
        bundle install
    - name: Run tests
      run: bundle exec rake rubocop
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: voxpupuli/vox-pupuli-tasks
        add_git_labels: true
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: voxpupuli/vox-pupuli-tasks
        add_git_labels: true
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
```

I also published a few docker modules with this. Since a few days I get the following errormessage:

```
Successfully built 65ffb4a2ea6a
Successfully tagged voxpupuli/vox-pupuli-tasks:latest
Successfully tagged voxpupuli/vox-pupuli-tasks:pr-217-merge
Successfully tagged voxpupuli/vox-pupuli-tasks:sha-0612700
Pushing image [voxpupuli/vox-pupuli-tasks:latest voxpupuli/vox-pupuli-tasks:pr-217-merge voxpupuli/vox-pupuli-tasks:sha-0612700]
The push refers to repository [docker.io/voxpupuli/vox-pupuli-tasks]
d0d252682376: Preparing
cb1d850665a1: Preparing
3da0bf188cbd: Preparing
97f83abe5a46: Preparing
91cd5a8e58ae: Preparing
fd74c6bcef3b: Preparing
9c6bf071bef9: Preparing
b84c9316c1db: Preparing
1620e857daea: Preparing
93a2bfafa84f: Preparing
54f362ba164c: Preparing
c4b1ff92c516: Preparing
446d8e2016ac: Preparing
50644c29ef5a: Preparing
fd74c6bcef3b: Waiting
9c6bf071bef9: Waiting
b84c9316c1db: Waiting
1fa5cdcb4f03: Waiting
0262166ecd22: Waiting
1bb9a3658531: Waiting
1620e857daea: Waiting
93a2bfafa84f: Waiting
54f362ba164c: Waiting
c4b1ff92c516: Waiting
446d8e2016ac: Waiting
50644c29ef5a: Waiting
denied: requested access to the resource is denied
exit status 1
Error: exit status 1
Usage:
  github-actions build-push [flags]

Flags:
  -h, --help   help for build-push
```

I'm not 100% sure what it means. Are the credentials wrong? I built a docker image locally and pushed it with my credentials and that worked. I set the same as github secrets for `DOCKER_USERNAME` and `DOCKER_PASSWORD`.

**Comment by osterman** [comment]
We were also using this GitHub action everywhere for a couple of months. Now it has started erroring with the same message.

> denied: requested access to the resource is denied

As a precaution, we rotated keys and tried again. Same outcome.

**Comment by osterman** [comment]
I suspect it's related to #92. 

![image](https://user-images.githubusercontent.com/52489/92501368-4d819780-f1b3-11ea-88d9-0e68c540ad5f.png)

**Comment by osterman** [comment]
We switched to `uses: docker/build-push-action@v2` and everything started working again.

**Comment by crazy-max** [comment]
@osterman,

> We switched to `uses: docker/build-push-action@v2` and everything started working again.

Inputs have changed in v2 (not GA for now). See [Usage section](https://github.com/docker/build-push-action/tree/v2#usage) and also [this workflow](https://github.com/crazy-max/test-docker-action/blob/master/.github/workflows/full.yml) as an example.

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.

**Comment by guptadikshant** [comment]
Hello Everyone,

Can anyone please provide any solution here. i tried many options but this access denied issue is not resolved.

Can anyone please help ?

Thanks,
Dikshant

**Comment by nileshsahitya9** [comment]
For building the image just use this command 

docker build -t {your docker username}/{name_of_the_image} .

for pushing the image

docker push{ your docker username}/{name_of_the_image}
